# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

services:
  - mongodb

branches:
  only:
    - master
    - 6.x

matrix:
  include:
    - rvm: 2.2
      jdk: oraclejdk8
      env: RAILS_VERSIONS=3.0

    - rvm: 2.3.8
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

    - rvm: 2.6.2
      jdk: oraclejdk8
      env: RAILS_VERSIONS=4.0,5.0,6.0

    - rvm: jruby-9.2.5.0
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

env:
  global:
    - ELASTICSEARCH_VERSION=7.2.0
    - TEST_ES_SERVER=http://localhost:9250
    - TEST_CLUSTER_PORT=9250
    - QUIET=true

before_install:
  - source ./travis_before_script.sh
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle version

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:all

notifications:
  disable: true
