# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

language: ruby

branches:
  only:
    - master
    - travis

rvm:
  - 1.9.3
  - 2.1.2

jdk:
  - openjdk7

env:
  - TEST_BUNDLE_GEMFILE=$PWD/elasticsearch/elasticsearch-rails/elasticsearch-model/gemfiles/3.0.gemfile
  - TEST_BUNDLE_GEMFILE=$PWD/elasticsearch/elasticsearch-rails/elasticsearch-model/gemfiles/4.0.gemfile

services:
  - mongodb

before_script:
  - ls -la /usr/share/elasticsearch/bin/elasticsearch
  - rake bundle:clean
  - rake bundle:install

script:
  - SERVER=launch TEST_CLUSTER_COMMAND=/usr/share/elasticsearch/bin/elasticsearch TEST_BUNDLE_GEMFILE=$TEST_BUNDLE_GEMFILE bundle exec rake test:all

notifications:
  disable: true
