# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

services:
  - mongodb

branches:
  only:
    - master
    - 6.x
    - 7.x

matrix:
  include:
    - rvm: 2.4
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

    - rvm: 2.5
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0,6.0

    - rvm: 2.6
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0,6.0

    - rvm: 2.7
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0,6.0

    - rvm: ruby-head
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0,6.0

    - rvm: jruby-9.2.9.0
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

  allow_failures:
    - rvm: ruby-head
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0,6.0

env:
  global:
    - ELASTICSEARCH_VERSION=7.6.2
    - TEST_ES_SERVER=http://localhost:9250
    - TEST_CLUSTER_PORT=9250
    - QUIET=true

before_install:
  - source ./.ci/travis_before_script.sh
  - gem update --system;
  - gem update bundler
  - gem --version
  - bundle version

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:all

notifications:
  disable: true
