# -----------------------------------------------------------------------------
# Configuration file for http://travis-ci.org/elasticsearch/elasticsearch-rails
# -----------------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

services:
  - mongodb
  - elasticsearch

branches:
  only:
    - master
    - travis
    - 5.x
    - 6.x
    - 2.x

matrix:
  include:
    - rvm: 2.2
      jdk: oraclejdk8
      env: RAILS_VERSIONS=3.0

    - rvm: 2.3
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

    - rvm: 2.4
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

    - rvm: jruby-9.1
      jdk: oraclejdk8
      env: RAILS_VERSIONS=5.0

    - rvm: 2.5
      jdk: oraclejdk8
      env: RAILS_VERSIONS=4.0,5.0

env:
  global:
    - ELASTICSEARCH_VERSION=7.0.0.alpha
    - QUIET=true


before_install:
  - wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/7.0.0/elasticsearch-${ELASTICSEARCH_VERSION}.deb
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.deb.sha512
  - shasum -a 512 -c elasticsearch-${ELASTICSEARCH_VERSION}.deb.sha512
  - sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH_VERSION}.deb
  - sudo service elasticsearch restart
  - gem update --system -q
  - gem update bundler -q
  - gem --version
  - bundle version

install:
  - bundle install
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:all

notifications:
  disable: true
